name: Fetch Metadata and Create PR
permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: none
  
on:
  push:
    branches:
      - master

jobs:
  fetch-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Fetch metadata and create file
        run: |
          # Read the URLs from the file and fetch metadata for each URL
          while IFS= read -r url; do
            # Fetch page title for the URL
            title=$(curl -s "$url" | grep -o '<title[^>]*>.*</title>' | sed -e 's/<[^>]*>//g' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            
            # Append the fetched data to the array
            fetched_data_array+=("{\"url\": \"$url\", \"title\": \"$title\"}")
          done < urls.txt

          # Create the output file with the fetched data
          echo "[${fetched_data_array[@]}]" > fetched_data.json

      - name: Create pull request
        id: demo-1
        uses: peter-evans/create-pull-request@18f7dc018cc2cd597073088f7c7591b9d1c02672 # v3.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          branch: auto-pr-branch
          base: master
          commit-message: Add fetched metadata
          title: Add fetched metadata
          committer: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}">
          author: ${{env.GIT_COMMIT_AUTHOR_NAME}} <${{env.GIT_COMMIT_AUTHOR_EMAIL}}">
          body: |
            This PR adds a file with the fetched metadata from URLs.

            Please review and merge it.

          path: fetched_data.json
